'use strict';
// tests for related
// Generated by serverless-mocha-plugin

const mod               = require('../handler.js');
const mochaPlugin       = require('serverless-mocha-plugin');
const lambdaWrapper     = mochaPlugin.lambdaWrapper;
const expect            = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-related'
};

const wrapped = lambdaWrapper.wrap(mod, { handler: 'related' });

describe('related', () => {
  const id = 'x3kxmfs';

  const resultKeys = [
    "channel.name",
    "created_time",
    "id",
    "owner.avatar_120_url",
    "owner.username",
    "title",
  ];

  before(function (done) {
    lambdaWrapper.init(liveFunction);
    done();
  });

  it('is an array of results', (done) => {
    wrapped.run({ query: { id } }, (err, response) => {
      expect(response).to.not.be.empty;
      done();
    });
  });

  it(`contains a value for all keys in results`, (done) => {
    wrapped.run({ query: { id } }, (err, response) => {
      response.forEach((result) => {
        resultKeys.forEach((key) => {
          expect(result[key]).to.not.be.undefined;
        });
      });
      done();
    });
  });

  it('correctly sets the limit', (done) => {
    var limit = 4;
    wrapped.run({ query: { id, limit } }, (err, response) => {
      expect(response).to.have.lengthOf(limit);
      done();
    });
  });

  it('returns a handled error when ?id= is missing', (done) => {
    wrapped.run({ query: {} }, (err, response) => {
      expect(err).to.match(/400/gi);
      done();
    });
  });

  it('returns a handled error when ?id= is invalid', (done) => {
    wrapped.run({ query: { id: '' } }, (err, response) => {
      expect(err).to.match(/400/gi);
      done();
    });
  });
});
